FROM ghcr.io/olwig/grok-build-boxed:latest

LABEL org.opencontainers.image.source="https://github.com/olwig/grok-build-boxed"

USER root
RUN echo "grokuser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/grokuser && \
    chmod 0440 /etc/sudoers.d/grokuser

USER grokuser

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["fish"]
