#!/usr/bin/env bash

set -euo pipefail
# TODO merge in grok launcher script and remove this script
# TODO implement HOST_WORK in conainter

# --pull: podman run --pull=newer
# --sudo: use sudo-latest instead of latest
do_pull=false
use_sudo=false
for arg in "$@"; do
	if [[ "$arg" == "--pull" ]]; then
		do_pull=true
	elif [[ "$arg" == "--sudo" ]]; then
		use_sudo=true
	fi
done

if [ "$use_sudo" = true ]; then
	image="ghcr.io/olwig/grok-build-boxed:sudo-latest"
else
	image="ghcr.io/olwig/grok-build-boxed:latest"
fi

pull_args=()
if [ "$do_pull" = true ]; then
	pull_args=(--pull=newer)
fi

# user name leaks in container anyways ...
HOST_WORK="$PWD"
CONTAINER_WORK="/mnt/$HOST_WORK"
podman run -it --rm \
	"${pull_args[@]}" \
	-v ~/.grok-build-boxed/:/home/grokuser:Z \
	-v "$HOST_WORK":"$CONTAINER_WORK":Z \
	-w "$CONTAINER_WORK" \
	--userns=keep-id:uid=1000,gid=1000 \
	--hostname grok-build-boxed \
	"$image"
