name: Build and push to GHCR

on:
  push:
    branches: [main]
    paths:
      - Containerfile
      - Containerfile.sudo
      - .github/workflows/ghcr.yml
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'dry-run (build only, do not push)'
        required: false
        type: choice
        options:
          - 'false'
          - 'true'
        default: 'true'
  # schedule weekly rebuild to update pkgs
  schedule:
    - cron: '33 3 * * 6'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      default: ${{ steps.filter.outputs.default }}
      sudo: ${{ steps.filter.outputs.sudo }}
      workflow: ${{ steps.filter.outputs.workflow }}
      force-all: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
      dryrun: ${{ github.event_name == 'workflow_dispatch' && inputs.dryrun == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            default:
              - Containerfile
            sudo:
              - Containerfile.sudo
            workflow:
              - .github/workflows/ghcr.yml

  build-default:
    needs: changes
    if: needs.changes.outputs.force-all == 'true' || needs.changes.outputs.default == 'true' || needs.changes.outputs.workflow == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set timestamp tag
        id: vars
        run: echo "timestamp=$(date -u +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.dryrun != 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.dryrun != 'true' }}
          load: ${{ github.event_name == 'workflow_dispatch' && inputs.dryrun == 'true' }}
          pull: ${{ needs.changes.outputs.force-all == 'true' }}
          no-cache: true
          #no-cache: ${{ needs.changes.outputs.force-all == 'true' }}
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.timestamp }}

  build-sudo:
    # sudo depens on default
    needs: [changes, build-default]
    if: needs.changes.outputs.force-all == 'true' || needs.changes.outputs.sudo == 'true' || needs.changes.outputs.workflow == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set timestamp tag
        id: vars
        run: echo "timestamp=$(date -u +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.dryrun != 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile.sudo
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.dryrun != 'true' }}
          load: ${{ github.event_name == 'workflow_dispatch' && inputs.dryrun == 'true' }}
          pull: ${{ needs.changes.outputs.force-all == 'true' }}
          no-cache: true
          #no-cache: ${{ needs.changes.outputs.force-all == 'true' }}
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}:sudo-latest
            ghcr.io/${{ github.repository }}:sudo-${{ steps.vars.outputs.timestamp }}
